name: CICD Pipeline
on:  
  push:
    tags:
      - v*
  pull_request:
    branches:    
      - main
      - devleop

jobs:
  Pipeline:
    uses: mottu-ops/pipeline-core/.github/workflows/container-nodejs-kubernetes.yaml@v2
    with:
      sonarExclusions: "<PATH_TO_EXCLUDE>,<PATH_TO_EXCLUDE_2>" # (opcional) Caso queira exluir pastas ou arquivos de serem analisados no sonarqube, separados por ,
      app_name: <APPNAME> # o mesmo nome do seu deployment no k8s    
      namespace: <NAMESPACE> # o mesmo nome do seu deployment no k8s                              
      bu: <BU> # no formato "rental-bu, delivery-bu, etc"
      df_path: <DOCKERFILE-PATH> # (opcional) caso seu Dockerfile não esteja na raiz do projeto
    secrets: inherit
