name: PR to Main
on: 
  pull_request:
    branches:    
      - main

jobs:
  Pipeline:
    uses: mottu-ops/pipeline-core/.github/workflows/container-dotnet-kubernetes.yaml@v1
    with:
      dotnetSln: "<PATH_TO_SOLUTION>.sln"
      dotnetSources: '-s "https://nuget.pkg.github.com/Mottu-ops/index.json" -s "https://api.nuget.org/v3/index.json"'
    secrets: inherit
